backend:
  name: git-gateway
  branch: dev

# to enable local testing/dev, uncomment local_backend and comment out publish_mode
# local_backend: true
publish_mode: editorial_workflow

media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in gray-matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", picker_utc: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown", required: true}
